name: Integration Tests

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
      branches:
        - main
        - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
        DB_DATABASE: pending
        DB_USER: root
        DB_PASSWORD: 'root'
        DB_HOST: localhost

    steps:
    - name: Start MySQL and create database
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE pending;' -uroot -proot
        mysql -e 'SHOW DATABASES;' -uroot -proot

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build Spring Boot app using Maven
      run: mvn clean install

    - name: Run Spring Boot app
      run: |
        nohup java -jar target/*.jar & sleep 30

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection and Generate Report
      run: newman run postman/Forex-Agile.postman_collection.json --reporters cli,html --reporter-html-export newman-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman-report.html
