name: Integration Tests

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
      branches:
        - main
        - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
        DB_DATABASE: pending
        DB_USER: root
        DB_PASSWORD: 'root'
        DB_HOST: localhost
        DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
        DATASOURCE_URL: jdbc:mysql://localhost:3306/pending
        DATASOURCE_BRAND: MYSQL
        DATASOURCE_USERNAME: root
        DATASOURCE_PASSWORD: 'root'
        FOREX_DEFAULT_ROLE: ${{ secrets.FOREX_DEFAULT_ROLE }}
        FXRATES_API_KEY: ${{ secrets.FXRATES_API_KEY}}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}


    steps:
    - name: Start MySQL and create database
      run: |
        sudo /etc/init.d/mysql start
        sleep 10
        mysql -e 'CREATE DATABASE pending;' -uroot -proot
        mysql -e 'SHOW DATABASES;' -uroot -proot
        sleep 10

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build Spring Boot app using Maven
      run: mvn clean install -P prod

    - name: Run Spring Boot app
      run: |
        nohup mvn spring-boot:run -P prod > spring-boot.log 2>&1 &
        sleep 30
      
    - name: Upload Spring Boot Logs
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-logs
        path: spring-boot.log

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection and Generate Report
      run: newman run postman/Forex-Agile.postman_collection.json --reporters cli,html --reporter-html-export newman-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman-report.html
