name: Run Postman Collection

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
      branches:
        - main
        - develop  

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection and Generate Report
      run: newman run postman/Forex-Agile.postman_collection.json --reporters cli,html --reporter-html-export newman-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman-report.html
